WINDOW_HEIGHT = 1200
WINDOW_WIDTH = 1600

class Params:
    WINDOW_HEIGHT = 800
    WINDOW_WIDTH = 1000


    WINDOW_LOWER_PART_HEIGHT = 250
    WINDOW_UPPER_PART_HEIGHT = 700

    PLOT_AREA_HEIGHT = WINDOW_LOWER_PART_HEIGHT
    LOAD_DATA_AREA_HEIGHT = WINDOW_LOWER_PART_HEIGHT

    LOAD_DATA_AREA_WIDTH = 120
    PLOT_AREA_WIDTH = 750





